---

services:
  enxame:
    build: .
    command: fastapi dev enxame --host 0.0.0.0
    ports:
      - "8000:8000"
    env_file: ".env"
    develop:
      watch:
        - action: sync
          path: ./enxame
          target: /home/app/enxame